version: "3"
services:
  api:
   build:
      context: .
      dockerfile: Dockerfile
   ports:
     - 3001:3001
   environment:
     - NODE_ENV=development
   container_name: mern-api
   networks:
     - mern-stack-net
   volumes:
    - ./api/src:/usr/app/src
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local